# Generated by Django 2.2.6 on 2019-10-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=20)),
                ('sub_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('stu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Student')),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Subject')),
            ],
        ),
    ]
