# Generated by Django 2.2.6 on 2019-10-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20191023_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
