# Generated by Django 2.2.6 on 2019-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20191023_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
